// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanD0jT68UUQ_tzIpY6NmgZJ9jkAebMC8',
    appId: '1:103480993491:web:29b612d1299b468a629626',
    messagingSenderId: '103480993491',
    projectId: 'whoami-app-1234',
    authDomain: 'whoami-app-1234.firebaseapp.com',
    storageBucket: 'whoami-app-1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSaqn5YqieJdVhyP27PegyqUfBxffj-Qs',
    appId: '1:103480993491:android:01a7595813486cc8629626',
    messagingSenderId: '103480993491',
    projectId: 'whoami-app-1234',
    storageBucket: 'whoami-app-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhve4RtYwqpApSOU9xznItdX4Y2b30OhQ',
    appId: '1:103480993491:ios:2f7ec60937ac4ac3629626',
    messagingSenderId: '103480993491',
    projectId: 'whoami-app-1234',
    storageBucket: 'whoami-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.whoamiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhve4RtYwqpApSOU9xznItdX4Y2b30OhQ',
    appId: '1:103480993491:ios:2f7ec60937ac4ac3629626',
    messagingSenderId: '103480993491',
    projectId: 'whoami-app-1234',
    storageBucket: 'whoami-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.whoamiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanD0jT68UUQ_tzIpY6NmgZJ9jkAebMC8',
    appId: '1:103480993491:web:46ffb2345cdb13c1629626',
    messagingSenderId: '103480993491',
    projectId: 'whoami-app-1234',
    authDomain: 'whoami-app-1234.firebaseapp.com',
    storageBucket: 'whoami-app-1234.firebasestorage.app',
  );
}






